/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContentIndexRouteImport } from './routes/content/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as MiningIndexRouteImport } from './routes/mining/index'
import { Route as MiningIdRouteImport } from './routes/mining/$id'
import { Route as OffersIndexRouteImport } from './routes/offers/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentIndexRoute = ContentIndexRouteImport.update({
  id: '/content/',
  path: '/content/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const MiningIndexRoute = MiningIndexRouteImport.update({
  id: '/mining/',
  path: '/mining/',
  getParentRoute: () => rootRouteImport,
} as any)
const MiningIdRoute = MiningIdRouteImport.update({
  id: '/mining/$id',
  path: '/mining/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersIndexRoute = OffersIndexRouteImport.update({
  id: '/offers/',
  path: '/offers/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mining/$id': typeof MiningIdRoute
  '/content/': typeof ContentIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/mining/': typeof MiningIndexRoute
  '/offers/': typeof OffersIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mining/$id': typeof MiningIdRoute
  '/content': typeof ContentIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/mining': typeof MiningIndexRoute
  '/offers': typeof OffersIndexRoute
  '/products': typeof ProductsIndexRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mining/$id': typeof MiningIdRoute
  '/content/': typeof ContentIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/mining/': typeof MiningIndexRoute
  '/offers/': typeof OffersIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mining/$id'
    | '/content/'
    | '/dashboard/'
    | '/mining/'
    | '/offers/'
    | '/products/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mining/$id'
    | '/content'
    | '/dashboard'
    | '/mining'
    | '/offers'
    | '/products'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/mining/$id'
    | '/content/'
    | '/dashboard/'
    | '/mining/'
    | '/offers/'
    | '/products/'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MiningIdRoute: typeof MiningIdRoute
  ContentIndexRoute: typeof ContentIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  MiningIndexRoute: typeof MiningIndexRoute
  OffersIndexRoute: typeof OffersIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/': {
      id: '/content/'
      path: '/content'
      fullPath: '/content/'
      preLoaderRoute: typeof ContentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mining/': {
      id: '/mining/'
      path: '/mining'
      fullPath: '/mining/'
      preLoaderRoute: typeof MiningIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mining/$id': {
      id: '/mining/$id'
      path: '/mining/$id'
      fullPath: '/mining/$id'
      preLoaderRoute: typeof MiningIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers/': {
      id: '/offers/'
      path: '/offers'
      fullPath: '/offers/'
      preLoaderRoute: typeof OffersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MiningIdRoute: MiningIdRoute,
  ContentIndexRoute: ContentIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  MiningIndexRoute: MiningIndexRoute,
  OffersIndexRoute: OffersIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
